include prorab.mk

$(eval $(call prorab-config, ../config))

this_name := png

this_soname := 0

this_srcs += png/png.c
this_srcs += png/pngerror.c
this_srcs += png/pngget.c
this_srcs += png/pngmem.c
this_srcs += png/pngpread.c
this_srcs += png/pngread.c
this_srcs += png/pngrio.c
this_srcs += png/pngrtran.c
this_srcs += png/pngrutil.c
this_srcs += png/pngset.c
this_srcs += png/pngtrans.c
this_srcs += png/pngwio.c
this_srcs += png/pngwrite.c
this_srcs += png/pngwtran.c
this_srcs += png/pngwutil.c

$(eval $(prorab-build-lib))
